yatube/posts/urls.py
# yatube/posts/urls.py (File of urls of the posts app)

from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    # Home page
    path('', views.index, name='home'),
    # Groups pages
    path('group/<slug:slug>/', views.group_posts, name='group_list')

]

yatube/yatube/urls.py
# yatube/yatube/urls.py (Main file url of the project)

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self) -> str:
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='posts'
    )
    group = models.ForeignKey(
        Group, on_delete=models.SET_NULL, blank=True, null=True,
        related_name='posts'
    )

    class Meta:
        ordering = ['-pub_date']

    def __str__(self) -> str:
        return self.text

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Group

POSTS_PER_PAGE = 10


def index(request):
    template = 'posts/index.html'
    posts = Post.objects.all()[:POSTS_PER_PAGE]
    context = {
        'text': 'Последние обновления на сайте Yatube',
        'posts': posts,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()[:POSTS_PER_PAGE]
    context = {
        'group': group,
        'posts': posts,
    }
    return render(request, template, context)

yatube/templates/base.html
{% load static %}

<!DOCTYPE html>
<!-- Используется html 5 версии -->
<html lang="ru">
  <!-- Язык сайта - русский -->
  <head>
    <meta charset="utf-8" />
    <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="{% static 'img/fav/fav.ico' %}" type="image" />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="{% static 'img/fav/apple-touch-icon.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="{% static 'img/fav/favicon-32x32.png' %}"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="{% static 'img/fav/favicon-16x16.png' %}"
    />
    <meta name="msapplication-TileColor" content="#000" />
    <meta name="theme-color" content="#ffffff" />
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

    <title>{% block title %} {{ title }} {% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      {% block content %} Контент не подвезли {% endblock %}
    </main>
    <!-- Использованы классы бустрапа: -->
    <!-- border-top: создаёт тонкую линию сверху блока -->
    <!-- text-center: выравнивает текстовые блоки внутри блока по центру -->
    <!-- py-3: контент внутри размещается с отступом сверху и снизу -->
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
  <p>© 2020 Copyright <span style="color: red">Ya</span>tube</p>
</footer>

yatube/templates/includes/header.html
{% load static %}

<header>
  <!-- Использованы классы бустрапа для создания типовой навигации 
  с логотипом -->
  <!-- В дальнейшем тут будет создано полноценное меню -->
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:home' %}">
        <img
          src="{% static 'img/logo.png' %}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt=""
        />
        <!-- тег span используется для добавления нужных стилей отдельным 
        участкам текста -->
        <span style="color: red">Ya</span>tube
      </a>
    </div>
  </nav>
</header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %} {% block content %}
<div class="container py-5">
  <h1>{{ group.title }}</h1>
  <p>{{ group.description }}</p>
  <article>
    {% for post in posts %} {% include 'posts/post_card.html' with post=post %}
    {% if not forloop.last %}
    <hr />
    {% endif %} {% endfor %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %} {% load static %} {% block content %}
<div class="container py-5">
  <h1>{{ text }}</h1>
  <article>
    {% for post in posts %} {% include 'posts/post_card.html' with post=post %}
    {% if post.group %}
    <a
      href="{% url 'posts:group_list' post.group.slug %}"
      title="{{ post.group }}"
      >все записи группы {{ post.group }}</a
    >
    {% endif %} {% if not forloop.last %}
    <hr />
    {% endif %} {% endfor %}
  </article>
</div>
{% endblock %}

yatube/templates/posts/post_card.html
<div>
  <ul>
    {% if post.group %}
    <li>Группа: {{ post.group }}</li>
    {% endif %}
    <li>Автор: {{ post.author.get_full_name }}</li>
    <li>Дата публикации: {{ post.pub_date|date:"d E Y" }}</li>
  </ul>
  <p>{{ post.text }}</p>
  {% if post.group %} {% endif %}
</div>